### PR TITLE
provide cljfmt as a leiningen plugin

### PR DESCRIPTION
**Pull request by maxcountryman**

### CODE REVIEW

**Comment by laforge49** [comment]
Did this manually. Thanks again!

**Comment by maxcountryman** [comment]
I'd recommend providing it as a plugin if you want to encourage collaboration and a standardized formatting policy--you might also consider a linter, like [eastwood](https://github.com/jonase/eastwood). Of course that's up to you to decide.

**Comment by laforge49** [comment]
Added manually and applied it.

Many thanks!

**Comment by laforge49** [comment]
It has been a while since I tried eastwood. But it is no go.

It just dies when it encounters a call to a static method defined in a
gen-class:

C:\Users\Bill\Documents\GitHub\aatree>lein eastwood
Compiling aatree.CountedSequence
== Eastwood 0.2.1 Clojure 1.7.0 JVM 1.8.0_31
Directories scanned for source files:
  src test
== Linting aatree.CountedSequence ==
== Linting aatree.nodes ==
Exception thrown during phase :eval of linting namespace aatree.nodes
CompilerException java.lang.RuntimeException: No such var:
aatree.CountedSequence/create, compiling:(aatree\nodes.clj:165:4)
        clojure.lang.Compiler.analyze (Compiler.java:6543)
        clojure.lang.Compiler.analyze (Compiler.java:6485)
        clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3737)
        clojure.lang.Compiler.analyzeSeq (Compiler.java:6725)
        clojure.lang.Compiler.analyze (Compiler.java:6524)
        clojure.lang.Compiler.analyze (Compiler.java:6485)
        clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:5861)
        clojure.lang.Compiler$FnMethod.parse (Compiler.java:5296)
        clojure.lang.Compiler$FnExpr.parse (Compiler.java:3925)
        clojure.lang.Compiler.analyzeSeq (Compiler.java:6721)
        clojure.lang.Compiler.analyze (Compiler.java:6524)
        clojure.lang.Compiler.access$300 (Compiler.java:38)
        clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:577)
        clojure.lang.Compiler.analyzeSeq (Compiler.java:6723)
        clojure.lang.Compiler.analyze (Compiler.java:6524)
        clojure.lang.Compiler.analyze (Compiler.java:6485)
        clojure.lang.Compiler.eval (Compiler.java:6786)
        clojure.lang.Compiler.eval (Compiler.java:6745)
        clojure.core/eval (core.clj:3081)

eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval/fn--3576
(jvm.clj:520)
        eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval
(jvm.clj:520)
        eastwood.analyze-ns/analyze-file/fn--4173/fn--4175
(analyze_ns.clj:278)
        eastwood.analyze-ns/analyze-file/fn--4173 (analyze_ns.clj:276)
        eastwood.analyze-ns/analyze-file (analyze_ns.clj:274)
        eastwood.analyze-ns/analyze-ns (analyze_ns.clj:327)
        eastwood.lint/lint-ns (lint.clj:569)
        eastwood.lint/eastwood-core/fn--6336 (lint.clj:1041)
        eastwood.lint/eastwood-core (lint.clj:1040)
        eastwood.lint/eastwood (lint.clj:1154)
        eastwood.lint/eastwood-from-cmdline (lint.clj:1167)
        clojure.lang.Var.invoke (Var.java:379)
        eastwood.versioncheck/run-eastwood (versioncheck.clj:15)
        user/eval21 (form-init6813611018281909398.clj:1)
        clojure.lang.Compiler.eval (Compiler.java:6782)
        clojure.lang.Compiler.eval (Compiler.java:6772)
        clojure.lang.Compiler.load (Compiler.java:7227)
        clojure.lang.Compiler.loadFile (Compiler.java:7165)
        clojure.main/load-script (main.clj:275)
        clojure.main/init-opt (main.clj:280)
        clojure.main/initialize (main.clj:308)
        clojure.main/null-opt (main.clj:343)
        clojure.main/main (main.clj:421)
        clojure.lang.Var.invoke (Var.java:383)
        clojure.lang.Var.applyTo (Var.java:700)
        clojure.main.main (main.java:37)
Caused by:
RuntimeException No such var: aatree.CountedSequence/create
        clojure.lang.Util.runtimeException (Util.java:221)
        clojure.lang.Compiler.resolveIn (Compiler.java:6993)
        clojure.lang.Compiler.resolve (Compiler.java:6963)
        clojure.lang.Compiler.analyzeSymbol (Compiler.java:6924)
        clojure.lang.Compiler.analyze (Compiler.java:6506)
        clojure.lang.Compiler.analyze (Compiler.java:6485)
        clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3737)
        clojure.lang.Compiler.analyzeSeq (Compiler.java:6725)
        clojure.lang.Compiler.analyze (Compiler.java:6524)
        clojure.lang.Compiler.analyze (Compiler.java:6485)
        clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:5861)
        clojure.lang.Compiler$FnMethod.parse (Compiler.java:5296)
        clojure.lang.Compiler$FnExpr.parse (Compiler.java:3925)
        clojure.lang.Compiler.analyzeSeq (Compiler.java:6721)
        clojure.lang.Compiler.analyze (Compiler.java:6524)
        clojure.lang.Compiler.access$300 (Compiler.java:38)
        clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:577)
        clojure.lang.Compiler.analyzeSeq (Compiler.java:6723)
        clojure.lang.Compiler.analyze (Compiler.java:6524)
        clojure.lang.Compiler.analyze (Compiler.java:6485)
        clojure.lang.Compiler.eval (Compiler.java:6786)
        clojure.lang.Compiler.eval (Compiler.java:6745)
        clojure.core/eval (core.clj:3081)

eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval/fn--3576
(jvm.clj:520)
        eastwood.copieddeps.dep2.clojure.tools.analyzer.jvm/analyze+eval
(jvm.clj:520)
        eastwood.analyze-ns/analyze-file/fn--4173/fn--4175
(analyze_ns.clj:278)
        eastwood.analyze-ns/analyze-file/fn--4173 (analyze_ns.clj:276)
        eastwood.analyze-ns/analyze-file (analyze_ns.clj:274)
        eastwood.analyze-ns/analyze-ns (analyze_ns.clj:327)
        eastwood.lint/lint-ns (lint.clj:569)
        eastwood.lint/eastwood-core/fn--6336 (lint.clj:1041)
        eastwood.lint/eastwood-core (lint.clj:1040)
        eastwood.lint/eastwood (lint.clj:1154)
        eastwood.lint/eastwood-from-cmdline (lint.clj:1167)
        clojure.lang.Var.invoke (Var.java:379)
        eastwood.versioncheck/run-eastwood (versioncheck.clj:15)
        user/eval21 (form-init6813611018281909398.clj:1)
        clojure.lang.Compiler.eval (Compiler.java:6782)
        clojure.lang.Compiler.eval (Compiler.java:6772)
        clojure.lang.Compiler.load (Compiler.java:7227)
        clojure.lang.Compiler.loadFile (Compiler.java:7165)
        clojure.main/load-script (main.clj:275)
        clojure.main/init-opt (main.clj:280)
        clojure.main/initialize (main.clj:308)
        clojure.main/null-opt (main.clj:343)
        clojure.main/main (main.clj:421)
        clojure.lang.Var.invoke (Var.java:383)
        clojure.lang.Var.applyTo (Var.java:700)
        clojure.main.main (main.java:37)

The following form was being processed during the exception:
(defn
 new-counted-seq
 ([node](CountedSequence/create %28new-counted-iterator node%29 identity))
 ([node i](CountedSequence/create %28new-counted-iterator node i%29 identity)))

Shown again with metadata for debugging (some metadata elided for brevity):
^{:line 163}
(^{:line 163} defn
 ^{:line 163, :tag ^{:line 163} CountedSequence} new-counted-seq
 ^{:line 164}
 (^{:line 164} [^{:line 164} node]
  ^{:line 165}
  (^{:line 165} CountedSequence/create
   ^{:line 165} (^{:line 165} new-counted-iterator ^{:line 165} node)
   ^{:line 165} identity))
 ^{:line 166}
 (^{:line 166} [^{:line 166} node ^{:line 166} i]
  ^{:line 167}
  (^{:line 167} CountedSequence/create
   ^{:line 167}
   (^{:line 167} new-counted-iterator ^{:line 167} node ^{:line 167} i)
   ^{:line 167} identity)))

An exception was thrown while analyzing namespace aatree.nodes
Lint results may be incomplete.  If there are compilation errors in
your code, try fixing those.  If not, check above for info on the
exception.

Stopped analyzing namespaces after aatree.nodes
due to exception thrown.  6 namespaces left unanalyzed.

If you wish to force continuation of linting after an exception in one
namespace, make the option map key :continue-on-exception have the
value true.

WARNING: This can cause exceptions to be thrown while analyzing later
namespaces that would not otherwise occur.  For example, if a function
is defined in the namespace where the first exception occurs, after
the exception, it will never be evaluated.  If the function is then
used in namespaces analyzed later, it will be undefined, causing
error.

== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 1
Subprocess failed
C:\Users\Bill\Documents\GitHub\aatree>

**Pull request closed without merging**
